kind = "web"
previewPath = "/"
title = "Postal TCP/IP"
version = "1.0.0"
id = "artifacts/postal-tcp-ip"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25274

[services.development]
run = "pnpm --filter @workspace/postal-tcp-ip run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/postal-tcp-ip", "run", "build" ]
publicDir = "artifacts/postal-tcp-ip/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25274"
BASE_PATH = "/"
